# Founder Diary - Production Docker Compose
# Prepared for future scaling: API separation, multiple instances, etc.

services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: founder-diary-postgres
    environment:
      POSTGRES_DB: founder_diary
      POSTGRES_USER: founder_user
      POSTGRES_PASSWORD: FounderDiary2024!
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./deployment/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U founder_user -d founder_diary"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: founder-diary-redis
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Next.js Application
  app:
    build:
      context: .
      dockerfile: deployment/Dockerfile
      args:
        - NEXT_PUBLIC_SUPABASE_URL=https://dummy-project.supabase.co
        - NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.dummy
        - SUPABASE_SERVICE_ROLE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.dummy-service
    container_name: founder-diary-app
    environment:
      - NODE_ENV=production
      - PORT=3000
      # Database
      - DATABASE_URL=postgresql://founder_user:FounderDiary2024!@postgres:5432/founder_diary
      # Authentication
      - NEXTAUTH_URL=https://founder-diary.com
      - NEXTAUTH_SECRET=P5801sh83lelWNnvDnJeaTs1bHX2Rd3WEXNBvqxEjRY=
      # Cache
      - REDIS_URL=redis://redis:6379
      # App URLs (prepared for future API separation)
      - NEXT_PUBLIC_APP_URL=https://founder-diary.com
      - NEXT_PUBLIC_API_URL=https://founder-diary.com/api
      # Supabase (legacy, remove after migration)
      - NEXT_PUBLIC_SUPABASE_URL=https://dummy-project.supabase.co
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.dummy
      - SUPABASE_SERVICE_ROLE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.dummy-service
    # Port removed - access via Nginx only (more secure)
    # ports:
    #   - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

  # pgAdmin - PostgreSQL Admin Interface
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: founder-diary-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@luftmist.shop
      PGADMIN_DEFAULT_PASSWORD: FounderDiary2024!
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    # Port removed - access via Nginx with domain pg.founder-diary.com
    # ports:
    #   - "5050:80"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  # Nginx Reverse Proxy (Handles SSL, routing, caching)
  nginx:
    image: nginx:alpine
    container_name: founder-diary-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./deployment/nginx.conf:/etc/nginx/nginx.conf
      - ./deployment/proxy_params.conf:/etc/nginx/proxy_params.conf
      - ./deployment/ssl:/etc/nginx/ssl
      - ./deployment/nginx-cache:/var/cache/nginx
    depends_on:
      - app
      - pgadmin
    restart: unless-stopped
    labels:
      - "com.founder-diary.description=Reverse proxy for founder-diary.com, pg.founder-diary.com"

volumes:
  postgres_data:
  redis_data:
  pgadmin_data:

networks:
  default:
    name: founder-diary-network
    driver: bridge

# Future scaling preparation:
# - Add api: service when separating backend
# - Add multiple app instances with load balancing
# - Add Redis Sentinel for high availability
# - Add PgBouncer for connection pooling
