version: "3.9"

networks:
  infra:
    external: true

volumes:
  caddy_data:
  caddy_config:

services:
  caddy:
    image: caddy:2.8
    container_name: caddy
    restart: unless-stopped
    networks: [infra]
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile:ro

  app:
    image: ghcr.io/founder-diary/founder-diary-app:latest
    container_name: founder-diary-app
    restart: unless-stopped
    networks: [infra]
    env_file:
      - .env
    expose:
      - "3000"
